{{- if .Values.config.requireGpuSupport }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-nfd-
  name: openshift-nfd
  namespace: openshift-nfd
spec:
  targetNamespaces:
  - openshift-nfd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  channel: {{ .Values.operators.nfd.installChannel }}
  installPlanApproval: {{ .Values.operators.nfd.installPlanApproval }}
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
