ARG now
ARG ubi_version

FROM quay.io/opendatahub/workbench-images:jupyter-datascience-ubi${ubi_version}-python-3.${ubi_version}-${now}

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt
