{{- if .Values.config.requireSingleModelServing }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-smesh-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: smesh-operator
  namespace: redhat-smesh-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: redhat-smesh-operator
spec:
  channel: {{ .Values.operators.servicemesh.installChannel }}
  installPlanApproval: {{ .Values.operators.servicemesh.installPlanApproval }}
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
