---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-create-imagestreams
  namespace: redhat-ods-applications
rules:
  - apiGroups:
      - 'image.openshift.io'
    resources:
      - imagestreams
    verbs:
      - get
      - watch
      - list
      - create
---
# Role Binding
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-create-imagestreams
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: rhoai-notebook-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-create-imagestreams
